SIGNTOOL = C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\Bin\signtool
	
.PHONY : install
install : $(OUTPUT)/suneido.exe
	copy /y $(OUTPUT)\\suneido.exe .
	$(SIGNTOOL) sign /p Fibulat3 /f Z:\std\documents\codecerts\mykey.pfx suneido.exe
	$(SIGNTOOL) timestamp /t http://timestamp.comodoca.com/authenticode suneido.exe
	copy /y suneido.exe "C:\Users\andrew\Documents\My Dropbox"
