AddFile('profileProgress.txt', '\r\n-------------------------------------------')
AddFile('profileProgress.txt', '\r\nallCA.go: Started')
AddFile('profileProgress.txt', '\r\nUse: Started')
Use('axonlib')
Use('Accountinglib')
Use('etalib')
Use('towlib')
Use('pcmiler')
Use('ticketlib')
Use('joblib')
Use('prlib')
Use('prcadlib')
Use('etaprlib')
Use('invenlib')
Use('wolib')
Use('polib')
Use('carslib')
Use('fuelinlib')
Use('groupslib')
Use('configlib')
AddFile('profileProgress.txt', '\r\nUse: Completed\r\nDemo_Data: Started')
Create_DemoData('CAD')
AddFile('profileProgress.txt', '\r\nDemo_Data: Completed\r\nTest: Started')
TestRunner.Run()
AddFile('profileProgress.txt', '\r\nTest: Completed')
AddFile('profileProgress.txt', '\r\nallCA.go: Completed')
Exit()