PutFile('profileProgress.txt', '\r\n-------------------------------------------')
AddFile('profileProgress.txt', '\r\nsetup.go: Started\r\nUse: Started')
Use('axonlib')
Use('Accountinglib')
Use('etalib')
Use('towlib')
Use('pcmiler')
Use('ticketlib')
Use('joblib')
Use('prlib')
Use('pruslib')
Use('etaprlib')
Use('invenlib')
Use('wolib')
Use('polib')
Use('carslib')
Use('fuelinlib')
Use('groupslib')
Use('configlib')
AddFile('profileProgress.txt', '\r\nUse: Completed\r\nGet_Changes: Started')
GetVersionControlChanges(Libraries())
AddFile('profileProgress.txt', '\r\nGet_Changes: Completed\r\nsetup.go: Completed')
Exit()
