AddFile('profileProgress.txt', '\r\n-------------------------------------------')
AddFile('profileProgress.txt', '\r\ntest.go: Started')
AddFile('profileProgress.txt', '\r\nUse: Started')
Use('stdlib')
AddFile('profileProgress.txt', '\r\nUse: Completed\r\nTest: Started')
TestRunner.Run()
AddFile('profileProgress.txt', '\r\nTest: Completed')
AddFile('profileProgress.txt', '\r\ntest.go: Completed')
Exit()